version: "3"

services:
  web:
    build: .
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./.env
    depends_on:
      - database
      - redis
    stdin_open: true
    tty: true

  database:
    image: postgres:12.5
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    ports:
      - "5900:5900"
    volumes:
      - ./tmp/downloads:/home/seluser/Downloads

  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  sidekiq:
    depends_on:
      - 'database'
      - 'redis'
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/usr/src/app
      - '/usr/src/app/tmp'
    env_file:
      - ./.env
volumes:
  db_data:
  redis:
